name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:                                         
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Install CPU-only PyTorch and tensorboard for CI
          pip install --extra-index-url https://download.pytorch.org/whl/cpu "torch" "torchvision"
          pip install tensorboard
          # commonly used tooling for progress bars in examples/tests
          pip install tqdm
          pip install -r requirements.txt || true
          pip install pytest
      - name: Run tests
        run: pytest -q
