name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:                                         
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # Install the package in editable mode without pulling runtime deps.
          # This avoids triggering an editable build that tries to install
          # heavy runtime dependencies listed in extras.
          pip install -e . --no-deps
          # Now install CPU-only PyTorch and test/doc tooling explicitly.
          pip install --extra-index-url https://download.pytorch.org/whl/cpu "torch" "torchvision"
          pip install tensorboard tqdm pytest
          # install any lightweight declared test requirements if present
          pip install -r requirements.txt || true
      - name: Run tests
        run: pytest -q
