name: docs-deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install docs requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
      - name: Generate API docs
        run: |
          sphinx-apidoc -o docs/source torchflow
      - name: Build HTML
        run: |
          python -m sphinx -b html docs/source docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          publish_branch: gh-pages
          keep_files: false
